version: "3.8"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/springbootrealtimeendtoend?allowPublicKeyRetrieval=true    
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: mythrishank
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root